version: 2
updates:
  - package-ecosystem: deno
    directories:
      - "/"
      - "/examples"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
